-- Binatna Shop - Supabase database setup
-- شغّل هذا الملف في Supabase > SQL Editor ثم أنشئ مستخدم الإدارة من Authentication.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'أخرى',
  price numeric not null default 0,
  old_price numeric,
  emoji text,
  tag text,
  sizes jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  description text,
  rating numeric not null default 0,
  reviews integer not null default 0,
  stock integer not null default 0,
  image text,
  images jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  wilaya text not null,
  address text,
  notes text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric not null default 0,
  delivery numeric not null default 0,
  total numeric not null default 0,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

-- قائمة الإدارة: أضف UUID الخاص بحساب الإدارة بعد إنشاء المستخدم.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.admin_users where user_id = auth.uid());
$$;

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "products public read" on public.products;
create policy "products public read" on public.products for select using (true);

drop policy if exists "products admin insert" on public.products;
create policy "products admin insert" on public.products for insert with check (public.is_admin());
drop policy if exists "products admin update" on public.products;
create policy "products admin update" on public.products for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "products admin delete" on public.products;
create policy "products admin delete" on public.products for delete using (public.is_admin());

drop policy if exists "orders admin read" on public.orders;
create policy "orders admin read" on public.orders for select using (public.is_admin());
drop policy if exists "orders admin update" on public.orders;
create policy "orders admin update" on public.orders for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin users self read" on public.admin_users;
create policy "admin users self read" on public.admin_users for select using (auth.uid() = user_id);

-- دالة آمنة لاستقبال طلبات المتجر من الصفحة العامة.
create or replace function public.place_order(
  p_name text,
  p_phone text,
  p_wilaya text,
  p_address text,
  p_notes text,
  p_items jsonb,
  p_delivery numeric
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_subtotal numeric := 0;
  v_item jsonb;
  v_product_id bigint;
  v_qty integer;
  v_price numeric;
  v_stock integer;
begin
  if length(trim(coalesce(p_name,''))) < 2 then raise exception 'اسم العميل غير صالح'; end if;
  if length(trim(coalesce(p_phone,''))) < 8 then raise exception 'رقم الهاتف غير صالح'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'السلة فارغة'; end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_product_id := (v_item->>'id')::bigint;
    v_qty := greatest(1, coalesce((v_item->>'qty')::integer,1));
    select price, stock into v_price, v_stock from public.products where id=v_product_id for update;
    if not found then raise exception 'المنتج غير موجود: %', v_product_id; end if;
    if v_stock < v_qty then raise exception 'المخزون غير كاف للمنتج: %', v_product_id; end if;
    v_subtotal := v_subtotal + (v_price * v_qty);
    update public.products set stock = stock - v_qty where id=v_product_id;
  end loop;

  insert into public.orders(customer_name,phone,wilaya,address,notes,items,subtotal,delivery,total,status)
  values(trim(p_name),trim(p_phone),trim(p_wilaya),trim(p_address),trim(coalesce(p_notes,'')),p_items,v_subtotal,coalesce(p_delivery,0),v_subtotal+coalesce(p_delivery,0),'new')
  returning id into v_id;
  return v_id;
end;
$$;

grant execute on function public.place_order(text,text,text,text,text,jsonb,numeric) to anon, authenticated;
